### ISSUE TITLE
Issue when loading some MIDI files

### ISSUE THREAD

**Issue by benjaminrall** [hwcrane/Piano-Midi-Visualiser#2]
When trying to load the attached MIDI file for Rush E the project crashes for some reason.

This is the error I get:
```
pygame 2.5.2 (SDL 2.28.3, Python 3.11.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "~\Piano-Midi-Visualiser\main.py", line 96, in <module>
    Main().mainloop()
    ^^^^^^
  File "~\Piano-Midi-Visualiser\main.py", line 25, in __init__
    self.piano_roll = PianoRoll(self.midiFile)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Piano-Midi-Visualiser\piano_roll.py", line 8, in __init__
    self.transcribed_song = self.transcribe_song(midiFile)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Piano-Midi-Visualiser\piano_roll.py", line 33, in transcribe_song
    note = midi_number_to_note(msg.note)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Piano-Midi-Visualiser\keymap.py", line 33, in midi_number_to_note
    return {
           ^
KeyError: 20
```

This is the problematic midi file:
[4_rush_e.zip](https://github.com/hwcrane/Piano-Midi-Visualiser/files/14856346/4_rush_e.zip)

**Comment by hwcrane** [comment]
The error is caused by the midi file you are using containing notes outside the range of a normal piano. This is clearly a attack campaign by the creator of an inferior Piano Midi Visualiser and will not be fixed
